config/routes.rb
Rails.application.routes.draw do

  resources :tweets
  resources :users

  get     '/login', to: 'sessions#new',    as: 'new_login'
  post    '/login', to: 'sessions#create', as: 'create_session'
  delete  '/logout', to: 'sessions#destroy', as: 'logout'

#change this back to login page as root_path
  root 'tweets#index' #why doesn't this say login in url?

end

app/models/tweet.rb
class Tweet < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :tweets, dependent: :destroy
  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  skip_before_filter :authenticate_user, only: [:show, :new, :create]
  before_action :current_user

  def authenticate_user
    unless user_logged_in?
      redirect_to new_login_path
    end
  end

  def current_user
    if user_logged_in?
      @current_user ||= User.find(session[:logged_in_user_id])
    end
  end

  def user_logged_in?
    session[:logged_in_user_id].present?
  end
  helper_method :user_logged_in?

  # protected
  # def user_session
  #   session[:logged_in_user_id]
  # end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :authenticate_user

  def new #login - where we collect the info
  end

  def create #where we create something with the info
    user = User.find_by_username(params[:username])
    if user.present? && user.authenticate(params[:password])
      #below is a cookie for the User object
      set_user_session(user)
      redirect_to tweets_path, notice: 'Successfully logged in.'
    else
      #when login is wrong
      flash[:alert] = "Username or Email did not match."
      render :new
    end
  end

  def destroy
    session[:logged_in_user_id] = nil
    redirect_to root_path, notice: 'Successfully logged out.'
  end

  private

  def set_user_session(user)
    session[:logged_in_user_id] = user.id
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: [:show, :edit, :update, :destroy]

  # GET /tweets
  # GET /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1
  # GET /tweets/1.json
  def show
    @tweet = Tweet.find(params[:id])
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets
  # POST /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)
    @tweet.user = current_user
    respond_to do |format|
      if @tweet.save
        format.html { redirect_to @tweet, notice: 'Tweet was successfully created.' }
      else
        format.html { render :new, notice: 'You must be logged in to leave a tweet.' }
      end
    end
  end

  # PATCH/PUT /tweets/1
  # PATCH/PUT /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to @tweet, notice: 'Tweet was successfully updated.' }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1
  def destroy
    respond_to do |format|
      if @tweet.user = current_user
        @tweet.destroy
        format.html { redirect_to tweets_url, notice: 'Tweet was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.html { render :index, notice: 'You cannot delete another users tweet.' }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def tweet_params
      params.require(:tweet).permit(:msg, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/1
  def show
  end

  # GET /users/new --- only the admin can make a new user
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    unless current_user == @username
      redirect_to :back, alert: "You are not authorized for that action."
    end
  end

  # POST /users
  def create
      @user = User.new(user_params)
      respond_to do |format|
        if @user.save
          format.html { redirect_to new_login_path, notice: 'User was successfully created.' }
        else
          format.html { render :new }
        end
      end
  end

  # PATCH/PUT /users/1
  def update
    if current_user == @user   #only the current_user can update herself
      respond_to do |format|
        if @user.update(user_params)
          format.html { redirect_to @user, notice: 'User was successfully updated.' }
        else
          format.html { render :edit }
        end
      end
    end
  end

  # DELETE /users/1
  def destroy
    if current_user == @user
      @user.destroy
      respond_to do |format|
        format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      end
    else
      redirect_to :back, alert: "You are not authorized for that action."
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterscaffold</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container-fluid">
  <div class='row'>
    <div class='col-md-3' 'col-offset-md-6'>
      <%= notice %>
      <%= alert %>
    </div>
  </div>

  <div class='row'>
      <div class='col-sm-8 col-sm-offset-2'>
        <section>
          <%= yield %>
        </section>
      </div>
  </div>

  <nav>
    <ul class="pager">
      <li><%= link_to('Tweets', tweets_path) %></li>
      <li><%= link_to('Users', users_path) %></li>
    </ul>
  </nav>
  <!-- <p> <%# user_session %> </p> -->

  <%= link_to( "Logout", logout_path, method: :delete) if user_logged_in? %>

  <footer class="pager"> <!-- add ul to this footer -->
    <nav>
      <li><%= link_to('Home', root_path) %></li>
    </nav>
  </footer>

</div>


<p>current_user:<%= @current_user.inspect %><br>
<%= params.inspect if Rails.env.development? %></p>

</body>
</html>

app/views/tweets/_form.html.erb
<%= form_for(@tweet) do |f| %>
  <% if @tweet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
      <% @tweet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :msg %><br>
    <%= f.text_field :msg %>
  </div>

  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tweets/edit.html.erb
<h1>Editing Tweet</h1>

<%= render 'form' %>

<%= link_to 'Show', @tweet %> |
<%= link_to 'Back', tweets_path %>

app/views/tweets/index.html.erb
<div class='container-fluid'>
  <div class='row'>
    <div class='col-md-4' 'col-offset-md-6'> <!-- Want to move listing tweets over by 4 units but this happening above th div -->
      <h1>Listing Tweets</h1>
    </div>
  </div>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Msg</th>
      <th>User</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @tweets.each do |tweet| %>
      <tr>
        <td><%= tweet.msg %></td>
        <td><%= tweet.user.username %></td>
        <td><%= link_to 'Show', tweet %></td>
        <td><%= link_to 'Edit', edit_tweet_path(tweet) %></td>
        <td><%= link_to 'Destroy', tweet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if user_logged_in? %>
<%= link_to 'New Tweet', new_tweet_path %>
<% else %>
<%= link_to 'Login', new_login_path %>
<% end %>

app/views/tweets/new.html.erb
<h1>New Tweet</h1>

<%= render 'form' %>

<%= link_to 'Back', tweets_path %>

app/views/tweets/show.html.erb
<p>
  <strong>Msg:</strong>
  <%= @tweet.msg %>
</p>

<p>
  <strong>User:</strong>
  <%= @tweet.user.username %>
</p>

<%= link_to 'Edit', edit_tweet_path(@tweet) %> |
<%= link_to 'Back', tweets_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1> /

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing Users</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>User ID#</th>
      <th>Username</th>
      <th colspan="3">Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.id %></td>
        <td><%= user.username %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %><br>

<% if !user_logged_in? %>
<%= link_to 'New Tweet', new_tweet_path %>
<% else %>
<%= link_to 'Login', new_login_path %>
<% end %><br>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

</ul>

<table class="table table-hover">
  <thead>
    <th> Tweets</th>
    <th> Time </th>
  </thead>
  <tbody>
    <% @user.tweets.each do |tweet| %>
    <tr>
      <td><%= tweet.msg %></td>
      <td><%= tweet.updated_at %></td>
    </tr>
  </tbody>
  <% end %>

</table>



<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', root_path %>